### ISSUE TITLE
Explore button missing details

### ISSUE THREAD

**Issue by vbvinay** [samitsolutions/fop#47] opened 2017-01-29 18:53 UTC
After clicking Explore button a new page open in this page images and details are missing.
![uploads/0846b849-a443-4f7a-87ce-73da5af36f8c/1.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0846b849-a443-4f7a-87ce-73da5af36f8c%2F1.png)

**Comment by codeyash** [comment] 2017-01-30 09:46
You changed parent category recommended. Set other category its parent which means no categories are parent. So nothing was coming.

You introduced this bug yourself. :)

It's not a bug but should know how categories are related to each other. One parent category with any other parent is required.

**Comment by codeyash** [comment] 2017-01-30 09:46
Now fixed using admin panel

**Closed by codeyash** 2017-01-30 09:46 UTC
Labels: 0 - Backlog, bug
