### ISSUE TITLE
ALPACA: iPhone View Bug When on Checkout

### ISSUE THREAD

**Issue by grethapouza** [samitsolutions/fop#192] opened 2017-04-26 18:31 UTC
Device: iPhone 6s
Version: 10.2.1 (not able to replicate on latest iOS  version 10.3.1)
Browser: Safari (latest version as found within 10.2.1 iPhone iOS)

Replication Steps:
1. Navigate to https://eatstax.com/alpaca-raleigh.
2. Add three items to the cart.
3. Navigate to checkout cart, when in chackout cart, if you attempt to scroll down to review your order, the view is frozen on the top part of the order, eventhough you are scrolling down (and can see the side navigation bar sliding) the contents in the view do not change. You are also not able to exit this view.

**Comment by codeyash** [comment] 2017-04-28 08:25
Using safari 10.1 desktop on Mac Sierra failed to produce issue.
I need more details on this. Screenshots.

If possible a video recording of this.

I'm suspecting one feature which I introduced in last release. This feature makes popup fullscreen on mobiles. This gives user a more native experience.

**Comment by codeyash** [comment] 2017-04-28 14:21
Please try here also:
dev.eatstax.com/zaika/

**Comment by codeyash** [comment] 2017-05-03 13:10
Release2015, September
OSiOS, v9
BrowserSafari
Screen Size4.7 in - 2.3 x 4.1 in
Resolution750 x 1334 px
Viewport375 x 667 dp


Working fine and the issue is fixed.

Closing.

Reopen if required.

**Closed by codeyash** 2017-05-03 13:10 UTC
Labels: bug, Help Wanted
